### ISSUE TITLE
DESIGN: Blog overview and detail page

### ISSUE THREAD

**Issue by nmuens** [neos/Neos.NeosIo#561]
## Goal
- Set up a blog overview page
- set up a blog detail page

## Sketch
https://www.figma.com/file/WB1WOA4tvJkbk0N2m25Aeq/neos.io-blog?type=design&node-id=0%3A1&mode=design&t=u247qdcCGoRHlqC6-1

## Current blog
- List page: https://www.neos.io/blog.html
- Details page: https://www.neos.io/blog/neos-8-3-release.html

## Todo
- [ ]  a designer need to [check my sketches and adapt them to the layout](https://www.figma.com/file/WB1WOA4tvJkbk0N2m25Aeq/neos.io-blog?type=design&node-id=0%3A1&mode=design&t=u247qdcCGoRHlqC6-1) done by JVMTech (**feel free to change!**)
  - [ ] details to show on list page
    - [ ]  date
    - [ ] tite
    - [ ] image (if existing)
    - [ ] Link to details page
    - [ ] pagination or "load more"  
  - [ ] details on detail page
    - [ ] title
    - [ ] date
    - [ ] authors (text)
    - [ ] text of blogpost
    - [ ] images
    - [ ] code blocks 
    - [ ] links to other recent blog posts
- [ ] implement design
- [ ] keep technical base for blog

**Comment by dmitrijkiltau** [comment]
PostGrid with Teaser: https://github.com/neos/Neos.NeosIo/pull/576

**Comment by minedesign-jl** [comment]
Blog Detail was updated in #686 according to Template in
https://design.penpot.app/#/workspace?team-id=5e0b7078-ec78-817e-8007-9f0678e59643&file-id=429aa6c1-d613-816d-8007-a029c6c9e158&page-id=986b3269-6855-80b2-8007-9f2c39c0723d&board-id=3854db42-6963-5424-9548-4c783dca6191

**Note** author images have been neglected since backend users are used as references for it and those do not have pictures.

### Open todos are:

- [ ] switch list of blog articles at the bottom for blog carousel once it has been merged
- [ ] design update for related content 
- [ ] image in content horizontally overflowing wrapper

**Comment by Sebobo** [comment]
@minedesign-jl blog carousel (as content element) is now merged
