### ISSUE TITLE
DESIGN: feature carousel

### ISSUE THREAD

**Issue by nmuens** [neos/Neos.NeosIo#563]
## Goal
- to have a component to mention the features of our product combined with a heading and a carousel function to see further details

## Inspiration
The component is inspired by an element on the salesforce website (see: https://www.salesforce.com/de/products/service/
)
<img width="1380" alt="image (18)" src="https://github.com/neos/Neos.NeosIo/assets/101414398/13d17652-508f-4d52-829c-1076bfc8bb8d">

## Tasks Design
- [ ] adapt the idea to our new neos.io layout
- [ ] please also think of a variant with icons
- [ ] also show, how this element would look like on mobile

## Task Dev
- [ ] code presentational components
- [ ] create component

**Comment by jonnitto** [comment]
Look at the integration from Neos Demo
