### ISSUE TITLE
Rebranding - NodeType Stage for content pages

### ISSUE THREAD

**Issue by nmuens** [neos/Neos.NeosIo#564]
## Goal
- we so far only have a design for the stage section for the homepage
- we need further variations of the stage section for subpages so it does not look the same way on every page
- especially the height should be reduced on subpages, so it does not take the whole screen height

### Variant 1
The variant is inspired by an element on the salesforce website (see: https://www.salesforce.com/de/products/b2b-marketing-automation/
)
<img width="1463" alt="image (19)" src="https://github.com/neos/Neos.NeosIo/assets/101414398/aa9551c8-74a4-4555-bae8-7753d7b6e05d">

### Variant 2
![image](https://github.com/neos/Neos.NeosIo/assets/101414398/94171c69-494c-4944-8e60-829b9ba49d4e)
- This variant should be able to have a small form on the left side instead of the text
- a logo bar

## Tasks Design
- [ ] adapt the idea to our new neos.io layout
  - [ ] for example for a page like `Switch to neos` 
![image](https://github.com/neos/Neos.NeosIo/assets/101414398/a2b37502-1244-49b7-8bb2-7c02b32fba76)
   - [ ] please include the pixels, which are part of our base layout
- [ ] variant 2
  - [ ]  Form (without steps): with the following fields: username, password, role (Dropdown), Type of interest in Neos (Dropdown), Button `start demo`
   - [ ] add logobar as part of the element `trusted by` and the company logos
   - [ ] to the neos community it is super important to show another logopbar with the sponsors
- [ ] also show, how this element would look like on mobile

## Task Dev
- [ ] code presentational components
- [ ] create nodetype
