### ISSUE TITLE
DESIGN: Testimonial

### ISSUE THREAD

**Issue by nmuens** [neos/Neos.NeosIo#565]
## Goal
- to show testimonials or highlighted cases
- we plan to show humans instead of websites whenever possible as humans interact with other humans
- it should store quotes but also normal text

## Inspiration
The component is inspired by an element on the Salesforce website
<img width="1167" alt="image (20)" src="https://github.com/neos/Neos.NeosIo/assets/101414398/6e2fb1dc-a7d7-42d6-a3c4-bf8dce3a0e12">

## Tasks Design
- [ ] adapt the idea to our new neos.io layout
- [ ] please also think of a variant without the photo of a person and a Screenshot instead
- [ ] please do also a left-right variant, where the photo and text change position
- [ ] also show, how this element would look like on mobile

## Task Dev
- [ ] code presentational components
- [ ] create component
- [ ] Make sure: it should store quotes **but also normal text**
