### ISSUE TITLE
DESIGN: Packages List

### ISSUE THREAD

**Issue by nmuens** [neos/Neos.NeosIo#566]
## goal
- we have a packages list [Packages list](https://www.neos.io/download-and-extend/packages.html) and [Package Detail] (https://www.neos.io/download-and-extend/packages/neos/neos-neos-development-collection.html)
- we have to adjust the style to make it fit to the new neos brand

## first design
@danielkestler did a first design. On 15th febrauary 2024 he worte `Made some quick drafts for the “Feature List” and “Packages” pages in the Figma file (on page “Screendesign Other Pages”) with a direction I think could fit. (It’s a bit rough but should give you an idea …)`. **Thank you very much!**
- darft here https://www.figma.com/file/YCFMrW1ti6g8vCnnSxxtTO/NEOS-Rebrand-Extern-NeosSprint?type=design&node-id=3156-249&mode=design&t=xTTauhTsdGKOO3JS-0

##  Tasks
- [ ] adjust style and find final design
  - [ ] JVMTech already told us, that the pixels should **not** be inverted
  - [ ] that the layout seems to flat at the moment and that the main colour should be used to keep the style
  - @maya-shines can organize a contact to JVMTech design team
